dist: xenial
language: r

r:
  - release

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev

cache:
  packages: true

python:
  - '3.7'

install:
  - pip install SigProfilerMatrixGenerator


warnings_are_errors: false

script: R -f test.R